=== AnandMurugan/kth-seds-2011-projects/ID2208/HW1/src/schemas/transcriptSchema.xsd
<?xml version="1.0"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->

<xsd:schema version="1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:xs="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">
    <xsd:element name="transcript">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="name" type="xsd:string"/>
                <xsd:element name="university" type="xsd:string"/>
                <xsd:element name="degree" type="xsd:string"/>
                <xsd:element name="year" type="xsd:int"/>
                <xsd:element name="courses">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element maxOccurs="unbounded" name="course">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="name" type="string" />
                                        <xsd:element name="code">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:string">
                                                    <xsd:pattern value="\[B-K]{2}\d{4}"/>
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>
                                        <xsd:element name="credits">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:decimal">
                                                    <xsd:minInclusive value="1.0"/>
                                                    <xsd:maxInclusive value="10.0"/>
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>
                                        <xsd:element name="grade"> 
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:string">
                                                    <xsd:length value="1"/>
                                                    <xsd:enumeration value="A"/>
                                                    <xsd:enumeration value="B"/>
                                                    <xsd:enumeration value="C"/>
                                                    <xsd:enumeration value="D"/>
                                                    <xsd:enumeration value="E"/>
                                                    <xsd:enumeration value="F"/>
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== AnandMurugan/kth-seds-2011-projects/ID2208/HW1/src/xml/transcript.xml
<?xml version="1.0" encoding="UTF-8"?>

<ns1:transcript
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://xml.netbeans.org/schema/transcriptSchema'
    xsi:schemaLocation='http://xml.netbeans.org/schema/transcriptSchema ../schemas/transcriptSchema.xsd'>
    <ns1:name>Anand</ns1:name>
    <ns1:university>KTH</ns1:university>
    <ns1:degree>Master of science</ns1:degree>
    <ns1:year>2012</ns1:year>
    <ns1:major>software engineering of distributed systems</ns1:major>
    <ns1:courses>
        <ns1:course>
            <ns1:name>Modern methods in Software Engineering</ns1:name>
            <ns1:code>ID2207</ns1:code>
            <ns1:credits>7.5</ns1:credits>
            <ns1:grade>B</ns1:grade>
        </ns1:course>
        <ns1:course>
            <ns1:name>Distributed system, basic course</ns1:name>
            <ns1:code>ID2201</ns1:code>
            <ns1:credits>7.5</ns1:credits>
            <ns1:grade>B</ns1:grade>
        </ns1:course>
        <ns1:course>
            <ns1:name>Distributed Artificial Intelligence and Intelligent Agents</ns1:name>
            <ns1:code>ID2209</ns1:code>
            <ns1:credits>7.5</ns1:credits>
            <ns1:grade>B</ns1:grade>
        </ns1:course>
        <ns1:course>
            <ns1:name>Network Programming with Java</ns1:name>
            <ns1:code>ID2212</ns1:code>
            <ns1:credits>7.5</ns1:credits>
            <ns1:grade>A</ns1:grade>
        </ns1:course>
    </ns1:courses>
</ns1:transcript>
