=== AnandMurugan/kth-seds-2011-projects/trunk/ID2208/HW1/src/schemas/employmentRecordXmlSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://xml.netbeans.org/schema/employmentRecordXmlSchema"
    xmlns:tns="http://xml.netbeans.org/schema/employmentRecordXmlSchema"
    elementFormDefault="qualified">
    <xsd:complexType name="basicInformationType">    
        <xsd:sequence>
            <xsd:element name="firstName" type="xsd:string"/>
            <xsd:element name="lastName" type="xsd:string"/>
            <xsd:element name="id" type="xsd:string"/>
            <xsd:element name="gender">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="M"/>
                        <xsd:enumeration value="F"/>
                    </xsd:restriction>    
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="extendedInformationType">
        <xsd:complexContent>
            <xsd:extension base="tns:basicInformationType">
                <xsd:sequence>
                    <xsd:element name="birthDate" type="xsd:date"/>
                    <xsd:element name="homeCountry" type="xsd:string"/>
                    <xsd:element name="race" type="xsd:string"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>
    <xsd:complexType name="contactInformationType">
        <xsd:sequence>
            <xsd:element name="email" type="xsd:string" />
            <xsd:element name="phone" type="xsd:string" />
        </xsd:sequence>    
    </xsd:complexType>
    <xsd:complexType name="locationType">
        <xsd:sequence>
            <xsd:element name="country" type="xsd:string"/>
            <xsd:element name="city" type="xsd:string"/>
            <xsd:element name="address" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:simpleType name="minBoundedDate">
        <xsd:restriction base="xsd:date">
            <xsd:minInclusive value="1901-01-01"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:complexType name="positionInfoType">
        <xsd:sequence>
            <xsd:element name="positionTitle" type="xsd:string"/>
            <xsd:element name="entranceDate" type="tns:minBoundedDate"/>
            <xsd:element name="exitDate" type="tns:minBoundedDate"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="extendedPositionInfoType">
        <xsd:complexContent>
            <xsd:extension base="tns:positionInfoType">
                <xsd:sequence>
                    <xsd:element name="hoursPerWeek" type="xsd:integer"/>
                    <xsd:element name="location" type="xsd:string"/>
                    <xsd:element name="exitReason" type="xsd:string"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>
    <xsd:element name="records">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="employmentRecord" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="employeeInfo" type="tns:extendedInformationType"/>
                            <xsd:element name="companyName" type="xsd:string"/>
                            <xsd:element name="companyContactInfo" type="tns:contactInformationType"/>
                            <xsd:element name="companyLocation" type="tns:locationType"/>                
                            <xsd:element name="startDate" type="tns:minBoundedDate"/>
                            <xsd:element name="endDate" type="tns:minBoundedDate"/>
                            <xsd:element name="positions">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="position" minOccurs="0" maxOccurs="unbounded" type="tns:extendedPositionInfoType"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>    
            </xsd:sequence>
        </xsd:complexType>    
    </xsd:element>   
</xsd:schema>

=== AnandMurugan/kth-seds-2011-projects/trunk/ID2208/HW2_JOB_SERV/src/java/xml/employment.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<ns0:records
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns0='http://xml.netbeans.org/schema/employmentRecordXmlSchema'
    xmlns:ns1="http://xml.netbeans.org/schema/commonSchema"
    xsi:schemaLocation='http://xml.netbeans.org/schema/employmentRecordXmlSchema ../schemas/employmentRecordXmlSchema.xsd'>
    <ns0:record personalNumber="881201-1234">
        <ns0:employmentRecord>
            <ns0:companyInfo name="Microsoft">
                <ns0:contactInfo>
                    <ns1:email>contact@microsoft.com
                    </ns1:email>
                    <ns1:phone>(425) 882-8080
                    </ns1:phone>
                </ns0:contactInfo>
            </ns0:companyInfo>
            <ns0:startDate>2010-01-01</ns0:startDate>
            <ns0:endDate>2011-06-01</ns0:endDate>
            <ns0:positions>
                <ns0:position>
                    <ns1:positionTitle>Intern</ns1:positionTitle>
                    <ns1:entranceDate>2010-01-01</ns1:entranceDate>
                    <ns1:exitDate>2010-05-30</ns1:exitDate>
                    <ns1:hoursPerWeek>30</ns1:hoursPerWeek>
                    <ns1:location>USA</ns1:location>
                    <ns1:exitReason>promoted</ns1:exitReason>
                </ns0:position>
                <ns0:position>
                    <ns1:positionTitle>developer</ns1:positionTitle>
                    <ns1:entranceDate>2010-06-01</ns1:entranceDate>
                    <ns1:exitDate>2011-06-01</ns1:exitDate>
                    <ns1:hoursPerWeek>40</ns1:hoursPerWeek>
                    <ns1:location>USA</ns1:location>
                    <ns1:exitReason>promoted</ns1:exitReason>
                </ns0:position>
            </ns0:positions>
        </ns0:employmentRecord>
    </ns0:record>

</ns0:records>

=== AnandMurugan/kth-seds-2011-projects/trunk/ID2208/HW1/src/xml/employmentRecordDatabase.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : employmentRecordXmlSchema.xml
    Created on : January 31, 2012, 10:56 PM
    Author     : julio
    Description:
        Purpose of the document follows.
-->

<ns0:records  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://xml.netbeans.org/schema/employmentRecordXmlSchema'
   xsi:schemaLocation='http://xml.netbeans.org/schema/employmentRecordXmlSchema ../schema/employmentRecordXmlSchema.xsd'>
    <ns0:employmentRecord>
        <ns0:employeeInfo>
            <ns0:firstName>Julio</ns0:firstName>
            <ns0:lastName>Vargas</ns0:lastName>
            <ns0:id>5930764</ns0:id>
            <ns0:gender>M</ns0:gender>
            <ns0:birthDate>1984-11-04</ns0:birthDate>
            <ns0:homeCountry>Bolivia</ns0:homeCountry>
        </ns0:employeeInfo>
        <ns0:companyInfo name="Microsoft">
            <ns0:contactInfo>
                <ns0:email>contact@microsoft.com</ns0:email>
                <ns0:phone>(425) 882-8080</ns0:phone>
            </ns0:contactInfo>
        </ns0:companyInfo>
        <ns0:startDate>2010-01-01</ns0:startDate>
        <ns0:endDate>2011-06-01</ns0:endDate>
        <ns0:positions>
            <ns0:position>
                <ns0:positionTitle>Intern</ns0:positionTitle>
                <ns0:entranceDate>2010-01-01</ns0:entranceDate>
                <ns0:exitDate>2010-05-30</ns0:exitDate>
                <ns0:hoursPerWeek>30</ns0:hoursPerWeek>
                <ns0:location>USA</ns0:location>
                <ns0:exitReason>promoted</ns0:exitReason>
            </ns0:position>
            <ns0:position>
                <ns0:positionTitle>developer</ns0:positionTitle>
                <ns0:entranceDate>2010-06-01</ns0:entranceDate>
                <ns0:exitDate>2011-06-01</ns0:exitDate>
                <ns0:hoursPerWeek>40</ns0:hoursPerWeek>
                <ns0:location>USA</ns0:location>
                <ns0:exitReason>promoted</ns0:exitReason>
            </ns0:position>
        </ns0:positions>
    </ns0:employmentRecord>
</ns0:records>
